# Generated by Django 4.2.7 on 2025-10-12 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Placa deve estar no formato ABC1234 ou ABC1D23",
                                regex="^[A-Z]{3}[0-9]{4}$|^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                            )
                        ],
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900, message="Ano deve ser maior que 1900"
                            ),
                            django.core.validators.MaxValueValidator(
                                2030, message="Ano deve ser menor que 2030"
                            ),
                        ]
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Caminhão"),
                            ("trailer", "Carreta"),
                            ("bus", "Ônibus"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("chassis_number", models.CharField(blank=True, max_length=100)),
                ("owner", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plate"],
            },
        ),
    ]
