# Generated by Django 4.2.7 on 2025-10-12 14:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("in_use", "Em Uso"),
                            ("in_stock", "Em Estoque"),
                            ("maintenance", "Em Manutenção"),
                            ("scrapped", "Sucateado"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("front_left", "Dianteiro Esquerdo"),
                            ("front_right", "Dianteiro Direito"),
                            ("rear_left", "Traseiro Esquerdo"),
                            ("rear_right", "Traseiro Direito"),
                            ("spare", "Estepe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "tread_depth",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tires",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["serial_number"],
            },
        ),
    ]
